-- Supabase SQL Editorで1回だけ実行します。
-- StorageバケットもこのSQLで作成します。

create table if not exists public.satellite_observations (
  scene_id text primary key,
  source_product_id text,
  satellite_collection text not null,
  captured_at timestamptz not null,
  observation_date date not null,
  ndci_mean double precision,
  ndti_mean double precision,
  fai_mean double precision,
  area_valid_m2 double precision,
  cloud_over_water double precision,
  valid_ratio double precision,
  image_bucket text not null,
  image_path text,
  csv_bucket text not null,
  csv_path text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists satellite_observations_captured_at_idx
  on public.satellite_observations (captured_at desc);

alter table public.satellite_observations enable row level security;
revoke all on table public.satellite_observations from anon, authenticated;
grant select on table public.satellite_observations to anon, authenticated;
grant all on table public.satellite_observations to service_role;

drop policy if exists "Public read satellite observations"
  on public.satellite_observations;
create policy "Public read satellite observations"
  on public.satellite_observations
  for select
  to anon, authenticated
  using (true);

create table if not exists public.satellite_ingestion_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null,
  finished_at timestamptz not null,
  window_start date not null,
  window_end date not null,
  status text not null check (status in ('success', 'no_data', 'failed')),
  accepted_count integer not null default 0 check (accepted_count >= 0),
  message text not null default ''
);

create index if not exists satellite_ingestion_runs_started_at_idx
  on public.satellite_ingestion_runs (started_at desc);

alter table public.satellite_ingestion_runs enable row level security;
revoke all on table public.satellite_ingestion_runs from anon, authenticated;
grant all on table public.satellite_ingestion_runs to service_role;
grant usage, select on sequence public.satellite_ingestion_runs_id_seq
  to service_role;

insert into storage.buckets (id, name, public)
values
  ('satellite-images', 'satellite-images', true),
  ('satellite-csv', 'satellite-csv', false)
on conflict (id) do nothing;
